# Generated by Django 5.0.6 on 2024-08-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('errormessage', models.TextField(blank=True, db_column='ErrorMessage', null=True)),
                ('errortime', models.TextField(blank=True, db_column='ErrorTime', null=True)),
            ],
            options={
                'db_table': 'error_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eventdescription',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'eventdescription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EventID', models.IntegerField(blank=True, db_column='EventID', null=True)),
                ('SourceName', models.TextField(blank=True, db_column='SourceName', null=True)),
                ('Level', models.TextField(blank=True, db_column='Level', null=True)),
                ('Channel', models.TextField(blank=True, db_column='Channel', null=True)),
                ('Message', models.TextField(blank=True, db_column='Message', null=True)),
                ('PredictedValue', models.TextField(blank=True, db_column='PredictedValue', null=True)),
                ('TimeGenerated', models.TextField(blank=True, db_column='TimeGenerated', null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('ALLOW', 'İzin Ver'), ('DROP', 'Engelle')], default='DROP', max_length=5)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], default='TCP', max_length=5)),
                ('source_ip', models.CharField(blank=True, max_length=45)),
                ('destination_ip', models.CharField(blank=True, max_length=45)),
                ('source_port', models.CharField(blank=True, max_length=5)),
                ('destination_port', models.CharField(blank=True, max_length=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iplogs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.IntegerField(blank=True, db_column='PID', null=True)),
                ('Process', models.TextField(blank=True, db_column='Process', null=True)),
                ('Local', models.TextField(blank=True, db_column='Local', null=True)),
                ('Remote', models.TextField(blank=True, db_column='Remote', null=True)),
                ('Protocol', models.TextField(blank=True, db_column='Protocol', null=True)),
                ('StartTime', models.TextField(blank=True, db_column='StartTime', null=True)),
                ('CommunicationProtocol', models.TextField(blank=True, db_column='CommunicationProtocol', null=True)),
                ('LocalIp', models.TextField(blank=True, db_column='LocalIP', null=True)),
                ('LocalPort', models.IntegerField(blank=True, db_column='LocalPort', null=True)),
                ('RemoteIp', models.TextField(blank=True, db_column='RemoteIP', null=True)),
                ('RemotePort', models.IntegerField(blank=True, db_column='RemotePort', null=True)),
            ],
            options={
                'db_table': 'IpLogs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sourcename', models.TextField(blank=True, db_column='SourceName', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('publishedat', models.TextField(blank=True, db_column='PublishedAt', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WatchPaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
            ],
            options={
                'db_table': 'watch_paths',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
