# Generated by Django 5.1.1 on 2024-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0002_errorlogs_eventdescription_events_filelogs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlogs',
            options={'managed': True, 'verbose_name_plural': 'Error Logs'},
        ),
        migrations.AlterModelOptions(
            name='eventdescription',
            options={'managed': True, 'verbose_name_plural': 'Event Description'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'managed': True, 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='filelogs',
            options={'managed': True, 'verbose_name_plural': 'File Logs'},
        ),
        migrations.AlterModelOptions(
            name='firewallrule',
            options={'managed': True, 'verbose_name_plural': 'Firewall Rules'},
        ),
        migrations.AlterModelOptions(
            name='iplogs',
            options={'managed': True, 'verbose_name_plural': 'Ip Logs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True, 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='watchpaths',
            options={'managed': True, 'verbose_name_plural': 'Watch Paths'},
        ),
        migrations.AddField(
            model_name='eventdescription',
            name='EventID',
            field=models.IntegerField(blank=True, db_column='EventID', null=True),
        ),
        migrations.AlterModelTable(
            name='firewallrule',
            table='firewallrule',
        ),
    ]
