# Generated by Django 5.1.1 on 2024-09-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0003_alter_errorlogs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdescription',
            name='EventID',
        ),
    ]
